{application,dhcp_server,
             [{modules,['Elixir.DhcpServer','Elixir.DhcpServer.Application',
                        'Elixir.DhcpServer.Dns','Elixir.DhcpServer.Handler',
                        'Elixir.DhcpServer.LeaseManager',
                        'Elixir.DhcpServer.LeaseManager.Lease',
                        'Elixir.DhcpServer.Packet','Elixir.DhcpServer.Socket',
                        'Elixir.DhcpServer.StatusReporter']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,crypto]},
              {description,"A DHCP server implementation in Elixir"},
              {registered,[]},
              {vsn,"1.0.0"},
              {mod,{'Elixir.DhcpServer.Application',[]}}]}.
